use crate::models::{Finding, ScanResult, Severity};
use crate::utils::ScanError;

pub fn generate(results: &[ScanResult], path: &str) -> Result<(), ScanError> {
    let total_findings: usize = results.iter().map(|r| r.statistics.total).sum();
    let total_critical: usize = results.iter().map(|r| r.statistics.critical).sum();
    let total_high: usize = results.iter().map(|r| r.statistics.high).sum();
    let total_medium: usize = results.iter().map(|r| r.statistics.medium).sum();
    let total_low: usize = results.iter().map(|r| r.statistics.low).sum();
    let total_info: usize = results.iter().map(|r| r.statistics.info).sum();

    let risk_score = total_critical * 25 + total_high * 15 + total_medium * 8 + total_low * 3 + total_info;
    let risk_level = if risk_score >= 100 { "Critical" }
        else if risk_score >= 50 { "High" }
        else if risk_score >= 20 { "Medium" }
        else if risk_score >= 5 { "Low" }
        else { "Info" };

    let mut html = String::new();
    html.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    html.push_str("<meta charset=\"UTF-8\">\n");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str("<title>offsecurity — Scan Report</title>\n");
    html.push_str("<style>\n");
    html.push_str(":root{--bg:#0d1117;--card:#161b22;--border:#30363d;--text:#c9d1d9;--muted:#8b949e;");
    html.push_str("--critical:#f85149;--high:#ff7b72;--medium:#d2991d;--low:#58a6ff;--info:#8b949e;}\n");
    html.push_str("*{margin:0;padding:0;box-sizing:border-box;}body{font-family:system-ui,sans-serif;");
    html.push_str("background:var(--bg);color:var(--text);line-height:1.6;}\n");
    html.push_str(".container{max-width:1100px;margin:0 auto;padding:2rem;}\n");
    html.push_str("h1{font-size:1.8rem;margin-bottom:.5rem;}h2{font-size:1.3rem;margin:1.5rem 0 .75rem;}\n");
    html.push_str(".card{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1.25rem;margin-bottom:1rem;}\n");
    html.push_str(".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:.75rem;}\n");
    html.push_str(".stat{padding:1rem;text-align:center;border-radius:6px;background:var(--card);border:1px solid var(--border);}\n");
    html.push_str(".stat .num{font-size:2rem;font-weight:700;}.stat .label{font-size:.8rem;color:var(--muted);}\n");
    html.push_str(".finding{padding:.75rem 0;border-bottom:1px solid var(--border);}\n");
    html.push_str(".finding:last-child{border-bottom:0;}\n");
    html.push_str(".sev{display:inline-block;padding:2px 8px;border-radius:4px;font-size:.75rem;font-weight:600;}\n");
    html.push_str(".sev.critical{background:var(--critical);color:#fff;}.sev.high{background:var(--high);color:#fff;}\n");
    html.push_str(".sev.medium{background:var(--medium);color:#fff;}.sev.low{background:var(--low);color:#fff;}\n");
    html.push_str(".sev.info{background:var(--info);color:#fff;}\n");
    html.push_str("</style>\n</head>\n<body>\n<div class=\"container\">\n");

    html.push_str("<h1>offsecurity Scan Report</h1>\n");
    html.push_str(&format!("<p style=\"color:var(--muted);\">Risk Score: <strong>{}</strong> — {}</p>\n",
        risk_score, risk_level));

    html.push_str("<h2>Executive Summary</h2>\n<div class=\"grid\">\n");
    for (label, count, color) in [
        ("Critical", total_critical, "var(--critical)"),
        ("High", total_high, "var(--high)"),
        ("Medium", total_medium, "var(--medium)"),
        ("Low", total_low, "var(--low)"),
        ("Info", total_info, "var(--info)"),
    ] {
        html.push_str(&format!(
            "<div class=\"stat\"><div class=\"num\" style=\"color:{}\">{}</div><div class=\"label\">{}</div></div>\n",
            color, count, label
        ));
    }
    html.push_str(&format!("<div class=\"stat\"><div class=\"num\">{}</div><div class=\"label\">Total</div></div>\n</div>\n",
        total_findings));

    for result in results {
        html.push_str(&format!("<h2>Target: {} <span style=\"color:var(--muted);font-size:.85rem;\">({:.1}s)</span></h2>\n",
            html_escape(&result.target_url), result.duration_secs));

        if result.findings.is_empty() {
            html.push_str("<div class=\"card\"><p>No findings.</p></div>\n");
        } else {
            html.push_str("<div class=\"card\">\n");
            for finding in &result.findings {
                html.push_str(&format_finding_html(finding));
            }
            html.push_str("</div>\n");
        }
    }

    html.push_str("<p style=\"margin-top:2rem;color:var(--muted);font-size:.8rem;\">");
    html.push_str("Generated by offsecurity — Authorized use only.</p>\n");
    html.push_str("</div>\n</body>\n</html>\n");

    std::fs::write(path, &html).map_err(|e| {
        ScanError::ReportError(format!("Failed to write HTML report: {}", e))
    })?;
    Ok(())
}

fn format_finding_html(f: &Finding) -> String {
    let sev_class = match f.severity {
        Severity::Critical => "critical",
        Severity::High => "high",
        Severity::Medium => "medium",
        Severity::Low => "low",
        Severity::Info => "info",
    };
    format!(
        "<div class=\"finding\">\n  <span class=\"sev {}\">{}</span> <strong>{}</strong> <span style=\"color:var(--muted);font-size:.8rem;\">({:.0}% conf.)</span>\n  <p style=\"margin-top:.25rem;\">{}</p>\n  <p style=\"color:var(--muted);font-size:.8rem;\">URL: {} | Check: {}</p>\n  <details style=\"margin-top:.25rem;\"><summary>Evidence & Fix</summary>\n    <p style=\"color:var(--muted);\"><strong>Evidence:</strong> {}</p>\n    <p style=\"color:var(--low);\"><strong>Fix:</strong> {}</p>\n  </details>\n</div>\n",
        sev_class, f.severity, html_escape(&f.title), f.confidence * 100.0,
        html_escape(&f.description), html_escape(&f.affected_url), html_escape(&f.check_type),
        html_escape(&f.evidence), html_escape(&f.recommendation),
    )
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
        .replace('"', "&quot;").replace('\'', "&#39;")
}
